// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVawwGnVkRYI5dxA4nFq4uIURJbY_-Y8g',
    appId: '1:360593979046:web:3a6fd5c7edc422e2bf2667',
    messagingSenderId: '360593979046',
    projectId: 'my-app-2025-desa00411',
    authDomain: 'my-app-2025-desa00411.firebaseapp.com',
    storageBucket: 'my-app-2025-desa00411.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7eyw3EYJDiUl-KSsOEEtv1ClZAFm0VZI',
    appId: '1:360593979046:android:b0e483726cca37ddbf2667',
    messagingSenderId: '360593979046',
    projectId: 'my-app-2025-desa00411',
    storageBucket: 'my-app-2025-desa00411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIspZWKILEKiK-ZXU7rbrLR-NrJaycPM',
    appId: '1:360593979046:ios:45e35c38920d148bbf2667',
    messagingSenderId: '360593979046',
    projectId: 'my-app-2025-desa00411',
    storageBucket: 'my-app-2025-desa00411.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIspZWKILEKiK-ZXU7rbrLR-NrJaycPM',
    appId: '1:360593979046:ios:45e35c38920d148bbf2667',
    messagingSenderId: '360593979046',
    projectId: 'my-app-2025-desa00411',
    storageBucket: 'my-app-2025-desa00411.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVawwGnVkRYI5dxA4nFq4uIURJbY_-Y8g',
    appId: '1:360593979046:web:6325f776be8ac55ebf2667',
    messagingSenderId: '360593979046',
    projectId: 'my-app-2025-desa00411',
    authDomain: 'my-app-2025-desa00411.firebaseapp.com',
    storageBucket: 'my-app-2025-desa00411.firebasestorage.app',
  );
}
